language: node_js
node_js:
- node
install:
- npm install
env:
  global:
    API_KEY:
      - secure: QULi3LII7EcGf84o44P+hU81dnbeuFRiGgrkmH+5YyQ8tAmUx88tc8N+hSIwiJN2YIbBwnNED5PevO9qfpwWS3zW3Du7u9wtufcDF/VS/FfUjFXYvcThIZ2c1i9ig8BEO/96AAt+F0mpWgr/2+6Z6Wy3uwD1DLbT8G8n/1zGUbz1T9GUfLzENvHPOOyxPkKErUe4zlPlGAqvL2XCq9FL/GOrGk8Y8wDzcFOKZSTr+Y/uDHSqBhLjSQH0DkqkZimTAhPbwhARaU54lI4kVuLl3Fhp/+QiRuJY/QT67PCCWitR2k7It0L8gOjVDcSvW/aDZwjKfkrZ7AYzS1UgYtzb9EuX506T1z5qyJKhm4yQNDHrgpj4/R3jKCOu9Ceiz37KbwF2jd4XDFDMoZQJaNdz7hrYf9t5tUgvbTX/etJaB+GqKeIuiNmfV9uKs+2Z9sp/3hMhts9qME0zdtnav9176goxA+PYZAyV2tCikvcylaIk54FAF8nS8i/0h/lWhXqzWCaYA2DmO2aWUHaGkD+vuSuhCtq6zlGkSk4XCIM0XRK2bAfXwUPNjUyaxjX3t0mfuIZkhnbWG8LuVCWhWT6Ugc3NM9G/MOPSvjcX0Mzd3uL/qQNJoeXe3qPzkz+3uliol8mDZ8DUcfzzOYAbYzai5TfgApsVzhmNM+I7zz5LXtA=
    API_SECRET:
      - secure: KAxf8IdxnEle+1muUxmwKPoYlTbSQroN9+/91TusrrvT7exk2fUAyRO7XprdN1/Uqoxm2t4uKi3GgE+Gp2X6sQq8XtovAo7oxvygE/bdnIqcgvyS340A+FXSwoUjj7TCwjW4sJntYzecBNuR+augaFnuQmKo+ks4NK4dmu5djbR7yOOZ9mT05DEk+LaDFVmkw5idgNvY5WnVEQox9Ow42KpEddT41Jn/7mB+wXjAQ73rCXOlfJkN5Qm2ZvepWggsl5AOLGSCdzBk+k4L39FG1JVggBENcqpm/aZiFTsF+Im+bWR2YCwTswoooUjFuZileuXnpwWXzkv8n+XPJ4k5iVve/o5hv/ZuoECDS0CGrqY+4BStMfOCWb22F8ujjeMBZTkvfFbmWPufclRLMt7/+WklSYotwHR9AC0ac7/P5TNGdBnRK7jOt7KtjAzn+xt5IeMB8yuwMdWq6OV4qsaFtXaA+HBMMSSwNEyrtPKP52k/Zt/HtEo00PprhtdE0Gam+Nd5eGXiDsoYiqjrQmaQ7NlkYz/+nEqjaQegPLiKV+Zv9/DK5T+v2yFQgP2i+2/BpXJVyQUTX5BehqiDYwljsJds3MJ4p+rsGCqU+RNpOfaeBFxcHagEAgvGKTMRPfIUYa5PM7uJ29pZQD/ZPf4FeMpK0uqs15D8uLYt9g0J8Ow=
script:
- npm test