language: node_js
node_js:
- node
install:
- npm install
script:
- export ${API_KEY}
- export ${API_SECRET}
- npm test
env:
  global:
  - secure: EmIqhpddBt4YSkuzaS05vgvK3w5E7orAoNe/YtD4ldEHg/Je7ZJdNe0jiKStTApt+p7aJR5AcuOxNLR4bHs6wTAddcmrg7/0csbpO20crwW+DggLcTHvIA2Y9aso5EdKe0dY8H3quWvoHyP2nh5hplPccbAIegDwb1VcS0AK11oYuOEIPAZdaaL7KvowGXY+JM5cFsywhmF67hPs/X2ALNj4r/wIofiiDmg91ZBL/UG11UQeoM4NHvWAqNIySHGYTadxEin/5WvIeZPTWO6AsLP/gJirpIix1lc6vmKp2cZNnVSx3d28eHZch1IjgBrHVmHF6TscR7luENwXljICShX1JB7jvS/EiPDonltBydJJtUx0YyLm4hZQoOyXRY5yAyAp8fwA+ouhB4lesdlaXYkwF32MlKEIsE0u5TRXFKtJ/lHFAjkF62b5SAkiUrv5UFrmUzzowlzHqpXj2ItVYZvU/bjKMNjuBy6mHYwY38F8Bqt83wIdy9hQMLmG4kXCd9X/0TvwKDJyMGYPBPT0QycEmCAh9Ri8yMZ6B0Eiie+fWrSweR3cPvmOCUKBaNTnKEGn1nmIvitFs9AJFpFZNdHwz5FVWX0KPB6B5aapzYFn1O4pDrh7iO/kcyiXeuAPaMbx2jNc53OUuud2BBaP8+JyMwqOoPfAggvzS5eLvp0=
  - secure: Od4G+42M1Bgi9WdXZ2e7TD67mIpNKYmxLy1K5KNgk1MyTvundli4sWIpA7iprjergr8fw0CKhRPXdPwjJnIaS/qvj6NGeYrp55xxsWtM9PCfqtBmWiwDLuNhQ6IFcTnoi1jIPY0iwd6at32ZofNUrAmXhMtzdF1AxEpQsDlvlD3DUpj2P35axXs1kSxF1n3nWBDEZImwDm8hrtAN8mnTaJ1IIUwVkb4SiSxxyosMGbfOCQ43T3mh7OL+LRGkeTVzTHS1MY1Snv0L2+UqbcDxxoNYbe7GxqRD0yNqd6NGk0x3mA99fXlrb4xe0J29sTOIH7A1Ow5SAMtA9eJlzeNyi9nIjnfMdrnpzC8vHMcBM5r0YrEACZH46wf4LGy/GQn3tjDgeZmHUEBGqjvxJ09R5y1v+S7V3xZ16eCm9zM4QOA0OGDAUjmj2PQkw5b4N94jLLgS1ZkSNPFOOJPiwkHLMc7OmQm2plgf9OyPcFo1RimrG3uYlxZI+4c+xrggiw9otcBqLTS63b32Z6qMR630jPyyR+Qy5IVGfMuY5Pt97WKYhtWMwKGJUntnBfc1qYIMySZpvSea1c13jBcUtwyPolriB21cE/aS9ISCIGk7X4hCNnEbVoi+fTV0o0TJf9oHb1V38PM+yppDbeRdlcvGPYUUhAzhBGu4kMn2rfE5uwA=
