language: node_js
node_js:
- node
install:
- npm install
env:
  global:
    API_KEY:
      - secure: nhxj3pL+52SqlcHSQQG7tjMQnQj+Q2W0jqpIpr4iE3ifIPLxMYGEI+XKq+TPR81Q7557HMgM3LCe0Ug7FuUESUt8mCJNZvSEXzLajTZUT46nq2dpWLkRDJ2y0b9EO3aA06IUs10j7OV4zoRI7zqyD8QuE4W2n/+piWhPWpBYDdKMdHA8ZWxRs6pERYScrWQrRIDf7wS32GdDSR8MBBtaedbJiiv0zkBF984ponTjuIGlTI22zPzDWV3Qku3VSQ62hrOS0M+OiaQW13Ienbzf9KKHCCnypm2ewA9O8yAQnl2+xZh7vTvR7QUsQA4kIYnwuO8MmBYGCs3NaWeC0TUBuSalELQd3WYA+LXNkje4MPJ2RXdnsdPkoFzxosK/4neAmVL4DhJ88PEBkJ1lm1iJqD+jZV/KAknCFHd+E0S+jMYXqqxT/QdJFCyS8DPDnECt7uAXRw/jv44yV5QoX80Bxgatez3gBjmCIUJmjjIpF44w49J6dmFCf24lI6WjlymIzq0HFWIJRpJ/88KROKv7PC8fqN+Jtl02+RrQgctLsGckX3uIY/BXJOWBQc+6IBwQhrBxdaneAfCgJbaOFpRlIz5F4dupoI1d1GPWLzlz/mAlk0CivbUXK5wKU0/rrrHgVPI7kuW8ovnE/OY3MFCQ1v5NU2VMoUdDG9+n2kdw/IM=
    API_SECRET:
      - secure: em/1Ms3VAd0bVFwXVZD6J2eY3Yct1LYLuIP3ijPA42DHExw2chNLcLfvb1shdnUwxPBm6FkWqH8gxsd9yWrkB/QSsVqlBD/pMmTk6tRep4nDmpbQ8rO/5iJPYd2t0ABhuNZlxmO9A4h5UTUzktkwp6q7n31yJDqNO81Yan2z24k37qOwA+Y8WQRXC3wSKGSImxvt/PIibeFRNB7bUAkDEkHepoFHIMPAd5uohIItTYUobVF7Z656uG7saWYyM7TS143K2ZWhBd7XvdIKJzJLLNpMym1eKfaT6uXtOGOcuHk4msf5JL3HTzYuJJi6jl870bPE4pdhSFYIc+zCOojGt2TbXuWf2VX9vo76QII4CB0GUEcGd2mn6Whcg3Ci8vEp7jHUMRkC3A9HlgMrzNFsT3S+Gwkg5bTQdZYscBH63bfhUZSCrReYIb2uOlGWZYpdM8jbLqWodYSiPDvnnj5C3AZDQTLhi6wkJUrzX9zhIunmK8XYIopVptry2fUF7H6bVrcsS7bWLlEGTsIR9VYONzuKwRKw6ceHQs63OsfgGI6zfZMrc1xqyoN+Agl4kdBxmLEqgKMYn2go2ZREOtXhfXWBHGMJwQVuVFUE4gPPRrDSwJQvu3NclEEYn05FZ7HL8rvPT9Z0mE7xE/Zh41droCM8gPqKp5iQnWQwKuIBMGw=
script:
- npm test
